### ISSUE TITLE
Formatting and documentation guidelines 

### ISSUE THREAD

**Issue by dahlek** [emolter/pylanetary#30]
It would be good to have a guide on how new code should/could be formatted, commented, and include examples. It seems like some of this exists, but examples can be included if not?

**Comment by emolter** [comment]
Thanks for submitting this @dahlek !  I will work on it.  I think the specific things brought up in the meeting were:

- example of a good docstring inside the contributing guidelines
- git for scientists tutorial, i.e., how to submit a pull request if you are new to git
- increase uniformity of docstrings already in pylanetary and their level of compliance with (e.g.) the Numpy standard

I feel like there are things that I missed, let me know!

**Comment by emolter** [comment]
@dahlek how do these changes to the contributing guidelines look? is it ok that I linked to resources instead of putting examples directly in-line?

**Comment by dahlek** [comment]
@emolter that's perf!
