### ISSUE TITLE
Compute solar zenith and emission angles

### ISSUE THREAD

**Issue by emolter** [emolter/pylanetary#39]
Building off of issue #38 it would be really helpful to finish the functionality for computing solar zenith and emission angles.  This should be relatively easy to do given what Nav already does, but it needs to be finished and tested.

**Comment by emolter** [comment]
In the most recent push to the active-dev branch, the ModelEllipsoid class (and therefore the ModelBody and Nav classes that inherit from it) have an attribute `mu0` by default, which represents the cosine of the solar incidence angle at each point on the body.  I also wrote a quick tutorial using some HST Jupiter data that shows how this can be used to make a limb-darkened disk with a Minnaert law, and that can be found [here](https://github.com/emolter/pylanetary/blob/active-dev/docs/nav-examples.ipynb).  @dahlek let me know if this covers your use-cases, and if not, what else you would like to see added

**Comment by dahlek** [comment]
Maybe in a similar vein, it would be helpful to have a routine to calculate airmasses of objects. At least for me, something like that in python would be a great help for planning observations

**Comment by emolter** [comment]
The airmass is already calculated by JPL Horizons, it's field number 8.  Within pylanetary, this means that it's accessible when you instantiate a Body object, e.g., `jup = Body('Jupiter', epoch=obs_time, location='@hst')` then `print(jup.ephem)`

**Comment by dahlek** [comment]
Oh sorry, I mean just for an RA/dec point in general. e.g. I'm making a plot of planet and calstar airmasses but the calstar stuff isn't as trivial

**Comment by dahlek** [comment]
kk sounds good. figured it might be a bit superfluous. And no, sorry, I haven't had a chance yet - I'll let you know when I do!

**Comment by dahlek** [comment]
@emolter this looks good! Got the nav object to happily shift around as well, I think I was having an issue with that before. 
The last thing we need for Nemesis retrievals is maps of azimuth angle; I currently have a code from Pat that can calculate that, and now that we have mu and mu0 we can use the normal vectors to calculate it I think

**Comment by emolter** [comment]
Thanks @dahlek I'm glad it's working!  I'm going to go ahead and close this issue.

What do you mean by azimuth angle in this context?  If you like, you can open another issue that requests this feature.

**Comment by dahlek** [comment]
I'll make a new issue
