### ISSUE TITLE
Restore compatability with Python 3.8

### ISSUE THREAD

**Issue by sloughran97** [emolter/pylanetary#57]
An error occurs when importing pylanetary using a Python 3.8 install. The issues seems to be the lack of a C compiler in Python 3.8 distributions in conda, which is required by recent Scipy versions.

Error message: version 'GLIBCXX_3.4.30' not found (required by .../scipy/spatial/fft/

Image below include full error message.
![image](https://github.com/emolter/pylanetary/assets/128156925/1fd317e4-a077-4b45-a588-c8adfa926111)

**Comment by emolter** [comment]
@sloughran97 Astropy will no longer even support 3.9 in the next release ([see this merged PR](https://github.com/astropy/astropy/pull/15603)), so I don't think there is any possible way to maintain back-compatibility with 3.8.  Marking this as closed
